### ISSUE TITLE
Load proposals without wallet being connected

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-governance#42] opened 2022-04-06 00:03 UTC
It seems that the "Last 5 Proposals" should load whether a wallet is connected or not. If it's necessary to have access to an account (beyond just a web3 connection), then we should prompt the user to connect a wallet.

https://www.loom.com/share/a0a75c64f28b4d56b785deaad3ded2f7

**Comment by sparrowDom** [comment] 2022-04-11 10:16
I think @tomlinton fixed this 18 days ago here: https://github.com/OriginProtocol/ousd-governance/commit/af241384fe118caef1084cb53fe32c89743ac869 . Can't reproduce it on localhost. 

Can't find when staging was deployed last time, since the error still seems to have persisted 5 days ago. 

Closing for now, let's reopen if the issue persists.

**Closed by sparrowDom** 2022-04-11 10:16 UTC
Labels: bug, ui/ux, P1
